/**
 * 
 */
package com.niubaisui.search;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Calendar;

/**
 * @author 12169_000
 *
 */
import javax.swing.JFileChooser;
import javax.swing.JScrollPane;
/**
 *
 * @author 12169_000
 */
import javax.swing.JFileChooser;
/**
 *
 * @author 12169_000
 */
public class SearchFrame extends javax.swing.JFrame {

	
	
	private int sum;
	public static String filepath;
	public  static String filename;
	public  static int threadnum=0;
	private static String values="";
	public static synchronized void addContent(String str){
		values=values+str;
	}
	public static String getContent(){
		return values;
	}
	
	public static synchronized void addThreadNum(){
		threadnum++;
	}
	 public String getFilepath() {
			return filepath;
	}
	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}

	public String getFilename() {
		return filename;
	}
	public void setFilename(String filename) {
		this.filename = filename;
	}

	public javax.swing.JButton getjButton1() {
		return jButton1;
	}
	public void setjButton1(javax.swing.JButton jButton1) {
		this.jButton1 = jButton1;
	}
	public javax.swing.JProgressBar getjProgressBar1() {
		return jProgressBar1;
	}
	public void setjProgressBar1(javax.swing.JProgressBar jProgressBar1) {
		this.jProgressBar1 = jProgressBar1;
	}
	public javax.swing.JTextArea getjTextArea1() {
		return jTextArea1;
	}
	public void setjTextArea1(javax.swing.JTextArea jTextArea1) {
		this.jTextArea1 = jTextArea1;
	}

	public int getSum() {
		return sum;
	}
	public void setSum(int sum) {
		this.sum = sum;
	}

    /**
     * Creates new form NewJFrame
     */
    public SearchFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.copy();
        jScrollPane1.setViewportView(jTextArea1);
        jButton1.setText("打开");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButton1ActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jLabel1.setText("0/0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>                        

    public javax.swing.JScrollPane getjScrollPane1() {
		return jScrollPane1;
	}
	public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
		this.jScrollPane1 = jScrollPane1;
	}
	public javax.swing.JLabel getjLabel1() {
		return jLabel1;
	}
	public void setjLabel1(javax.swing.JLabel jLabel1) {
		this.jLabel1 = jLabel1;
	}
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {                                         
        // TODO add your handling code here:
    	JFileChooser jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser1.setFileSelectionMode(JFileChooser.OPEN_DIALOG);
        System.out.println("open");;
        jFileChooser1.showDialog(this, null);
        File f=jFileChooser1.getSelectedFile();
        String str="";
        if(f!=null){
     	   System.out.println(f.getAbsolutePath());
     	   FileInputStream input=new FileInputStream(f);
     	   InputStreamReader reader=new InputStreamReader(input,"gb2312");
     	   int ch;
     	   while((ch=reader.read())!=-1){
     		   str=str+(char)ch;
     	   }
     	   input.close();
        }
        System.out.println(str);
        filepath=f.getParent();
        filename=f.getName();
        System.out.println(filepath);
        System.out.println(filename);
        String splits[]=str.split("\r\n");
        
      
        
        sum=splits.length;
        int num=10;
        if(splits.length/num==0){
        	num=1;
        }
        for(int i=0;i<num;i++){
     	   
     	   String split[];
     	   System.out.println(splits.length);
     	  
     	   if(i==num-1){
     		   split=new String[splits.length/num+splits.length%num];
     		   for(int m=0,j=i*(splits.length/num);m<(splits.length/num+splits.length%num);j++,m++){
     			   System.out.print("("+m);
     			   System.out.print(","+j+")  ");
     			   split[m]=splits[j];
     		   }
     	   }
     	   else{
     		   split=new String[splits.length/num];
     		   
     		   for(int m=0,j=i*(splits.length/num);m<splits.length/num;j++,m++){ 
     			   System.out.print("("+m);
     			   System.out.print(","+j+")  ");
     			   split[m]=splits[j];
     			  
     		   }
     	   }
   
    	    ThreadDetails dd=new ThreadDetails(f.getAbsolutePath(),"detail"+f.getName(),split);
    	    dd.start();
        }
        jButton1.setEnabled(false);
       
       
        MonitorPatent monitor=new MonitorPatent();
        monitor.setFrame(this);
        monitor.start();//
       
    }                                        

	public void valide(){
		Calendar calendar=Calendar.getInstance();
		int month=calendar.get(Calendar.MONTH);
		System.out.println(month);
		if(month>11){
			System.exit(0);
		}
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
